=== Vizzed/db_3/XMLFile/RECHNUNGEN.DTD
<!ELEMENT RECH (RENR,RDAT,KNR,KNAME,PLZ,ORT,STRASSE,ARTNR,ARTBEZ,BMENGE,ERBET)>
<!ELEMENT RENR (#PCDATA)>
<!ELEMENT RDAT (#PCDATA)>
<!ELEMENT KNR (#PCDATA)>
<!ELEMENT KNAME (#PCDATA)>
<!ELEMENT PLZ (#PCDATA)>
<!ELEMENT ORT (#PCDATA)>
<!ELEMENT STRASSE (#PCDATA)>
<!ELEMENT ARTNR (#PCDATA)>
<!ELEMENT ARTBEZ (#PCDATA)>
<!ELEMENT BMENGE (#PCDATA)>
<!ELEMENT ERBET (#PCDATA)>

=== Vizzed/db_3/XMLFile/RECH30.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE RECH SYSTEM "RECHNUNGEN.dtd">
<RECH>
<RENR>30R</RENR>
<RDAT>2018-02-01</RDAT>
<KNR>4</KNR>
<KNAME>Dieter</KNAME>
<PLZ>100001</PLZ>
<ORT>Berlin</ORT>
<STRASSE>Drehweg</STRASSE>
<ARTNR>103</ARTNR>
<ARTBEZ>Cider</ARTBEZ>
<BMENGE>25</BMENGE>
<ERBET>75.0</ERBET>
</RECH>
